name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    name: CI Build
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore Dependencies
      run: dotnet restore ConsoleCalculatorApplication.sln

    - name: Build
      run: dotnet build --no-restore ConsoleCalculatorApplication.sln

    - name: Test
      run: dotnet test ConsoleCalculatorApplication.sln --configuration Debug --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage
      
    - name: Codecov upload
      uses: codecov/codecov-action@v3